// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Maliev.QuotationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.QuotationService.Infrastructure.Migrations
{
    [DbContext(typeof(QuotationDbContext))]
    partial class QuotationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<JsonDocument>("ChangedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("ix_audit_log_entries_action_type");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_log_entries_entity_id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_log_entries_entity_type");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_log_entries_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_log_entries_user_id");

                    b.HasIndex("EntityType", "EntityId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_entries_entity_type_entity_id_timestamp");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ContactInfo")
                        .HasColumnType("jsonb")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<JsonDocument>("MergeHistory")
                        .HasColumnType("jsonb")
                        .HasColumnName("merge_history");

                    b.PrimitiveCollection<List<Guid>>("MergedFromIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("merged_from_ids");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_customers_is_deleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_customers_phone_number");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.DiscountStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorizationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("authorization_reason");

                    b.Property<string>("Conditions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("conditions");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<Guid>("QuotationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_version_id");

                    b.HasKey("Id")
                        .HasName("pk_discount_structures");

                    b.HasIndex("QuotationVersionId")
                        .HasDatabaseName("ix_discount_structures_quotation_version_id");

                    b.ToTable("discount_structures", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.FileReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_type");

                    b.Property<bool?>("IsManifold")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manifold");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.Property<Guid?>("RfqId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfq_id");

                    b.Property<double?>("SupportVolumeCm3")
                        .HasColumnType("double precision")
                        .HasColumnName("support_volume_cm3");

                    b.Property<double?>("SurfaceAreaCm2")
                        .HasColumnType("double precision")
                        .HasColumnName("surface_area_cm2");

                    b.Property<int?>("TriangleCount")
                        .HasColumnType("integer")
                        .HasColumnName("triangle_count");

                    b.Property<Guid>("UploadServiceFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_service_file_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<double?>("VolumeCm3")
                        .HasColumnType("double precision")
                        .HasColumnName("volume_cm3");

                    b.HasKey("Id")
                        .HasName("pk_file_references");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("ix_file_references_quotation_id");

                    b.HasIndex("RfqId")
                        .HasDatabaseName("ix_file_references_rfq_id");

                    b.HasIndex("UploadServiceFileId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_references_upload_service_file_id");

                    b.ToTable("file_references", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileReference_Entity", "(\"rfq_id\" IS NOT NULL AND \"quotation_id\" IS NULL) OR (\"rfq_id\" IS NULL AND \"quotation_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.InternalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.Property<Guid?>("RfqId")
                        .HasColumnType("uuid")
                        .HasColumnName("rfq_id");

                    b.HasKey("Id")
                        .HasName("pk_internal_notes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_internal_notes_created_at");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("ix_internal_notes_quotation_id");

                    b.HasIndex("RfqId")
                        .HasDatabaseName("ix_internal_notes_rfq_id");

                    b.ToTable("internal_notes", null, t =>
                        {
                            t.HasCheckConstraint("CK_InternalNote_Entity", "(\"rfq_id\" IS NOT NULL AND \"quotation_id\" IS NULL) OR (\"rfq_id\" IS NULL AND \"quotation_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.MaterialReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("integer")
                        .HasColumnName("availability_status");

                    b.Property<DateTime>("CachedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("MaterialCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_category");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("material_name");

                    b.Property<Guid>("MaterialServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_service_id");

                    b.Property<JsonDocument>("MechanicalProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("mechanical_properties");

                    b.Property<JsonDocument>("PhysicalProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("physical_properties");

                    b.PrimitiveCollection<List<string>>("SupportedProcesses")
                        .HasColumnType("text[]")
                        .HasColumnName("supported_processes");

                    b.HasKey("Id")
                        .HasName("pk_material_references");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_material_references_expires_at");

                    b.HasIndex("MaterialServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_material_references_material_service_id");

                    b.ToTable("material_references", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BillingIdentityType")
                        .HasColumnType("integer")
                        .HasColumnName("billing_identity_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("SourceProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_project_id");

                    b.Property<string>("SourceProjectNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_project_number");

                    b.Property<Guid?>("SourceRfqId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_rfq_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("ValidityPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("validity_period_end");

                    b.Property<DateOnly>("ValidityPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("validity_period_start");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_quotations");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_quotations_current_version_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_quotations_customer_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_quotations_is_deleted");

                    b.HasIndex("SourceProjectId")
                        .HasDatabaseName("ix_quotations_source_project_id");

                    b.HasIndex("SourceProjectNumber")
                        .HasDatabaseName("ix_quotations_source_project_number");

                    b.HasIndex("SourceRfqId")
                        .HasDatabaseName("ix_quotations_source_rfq_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_quotations_status");

                    b.HasIndex("ValidityPeriodEnd")
                        .HasDatabaseName("ix_quotations_validity_period_end");

                    b.ToTable("quotations", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.QuotationLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("ManufacturingProcess")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturing_process");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("material_name");

                    b.Property<JsonDocument>("MaterialProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("material_properties");

                    b.Property<Guid>("MaterialServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_service_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("quantity_unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_quotation_line_items");

                    b.HasIndex("VersionId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_quotation_line_items_version_id_line_number");

                    b.ToTable("quotation_line_items", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.QuotationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("change_summary");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<JsonDocument>("DeliveryExpectations")
                        .HasColumnType("jsonb")
                        .HasColumnName("delivery_expectations");

                    b.Property<string>("GeneratedByDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("generated_by_display_name");

                    b.Property<decimal>("ManualDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("manual_discount_amount");

                    b.Property<string>("PdfArtifactStoragePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("pdf_artifact_storage_path");

                    b.Property<string>("PdfArtifactUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("pdf_artifact_url");

                    b.Property<DateTime?>("PdfGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pdf_generated_at");

                    b.Property<string>("ProjectSnapshotHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("project_snapshot_hash");

                    b.Property<string>("ProjectSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("project_snapshot_json");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping_cost");

                    b.Property<string>("SpecialTerms")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("special_terms");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_quotation_versions");

                    b.HasIndex("QuotationId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_quotation_versions_quotation_id_version_number");

                    b.ToTable("quotation_versions", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Rfq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedStaffUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_staff_user_id");

                    b.Property<int>("ChannelSource")
                        .HasColumnType("integer")
                        .HasColumnName("channel_source");

                    b.Property<Guid?>("ConvertedToQuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_to_quotation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<JsonDocument>("RequestDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_details");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rfqs");

                    b.HasIndex("AssignedStaffUserId")
                        .HasDatabaseName("ix_rfqs_assigned_staff_user_id");

                    b.HasIndex("ChannelSource")
                        .HasDatabaseName("ix_rfqs_channel_source");

                    b.HasIndex("ConvertedToQuotationId")
                        .HasDatabaseName("ix_rfqs_converted_to_quotation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_rfqs_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_rfqs_customer_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_rfqs_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rfqs_status");

                    b.HasIndex("ChannelSource", "Status", "CreatedAt")
                        .HasDatabaseName("ix_rfqs_channel_source_status_created_at");

                    b.ToTable("rfqs", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.StaffRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff_roles");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_roles_role_name");

                    b.ToTable("staff_roles", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_~");

                    b.ToTable("outbox_message");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.DiscountStructure", b =>
                {
                    b.HasOne("Maliev.QuotationService.Domain.Entities.QuotationVersion", "QuotationVersion")
                        .WithMany("DiscountStructures")
                        .HasForeignKey("QuotationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discount_structures_quotation_versions_quotation_version_id");

                    b.Navigation("QuotationVersion");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.FileReference", b =>
                {
                    b.HasOne("Maliev.QuotationService.Domain.Entities.Quotation", "Quotation")
                        .WithMany("FileReferences")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_file_references_quotations_quotation_id");

                    b.HasOne("Maliev.QuotationService.Domain.Entities.Rfq", "Rfq")
                        .WithMany("FileReferences")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_file_references_rfqs_rfq_id");

                    b.Navigation("Quotation");

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.InternalNote", b =>
                {
                    b.HasOne("Maliev.QuotationService.Domain.Entities.Quotation", "Quotation")
                        .WithMany("InternalNotes")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_internal_notes_quotations_quotation_id");

                    b.HasOne("Maliev.QuotationService.Domain.Entities.Rfq", "Rfq")
                        .WithMany("InternalNotes")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_internal_notes_rfqs_rfq_id");

                    b.Navigation("Quotation");

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Quotation", b =>
                {
                    b.HasOne("Maliev.QuotationService.Domain.Entities.QuotationVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quotations_quotation_versions_current_version_id");

                    b.HasOne("Maliev.QuotationService.Domain.Entities.Customer", "Customer")
                        .WithMany("Quotations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotations_customers_customer_id");

                    b.HasOne("Maliev.QuotationService.Domain.Entities.Rfq", "SourceRfq")
                        .WithMany()
                        .HasForeignKey("SourceRfqId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quotations_rfqs_source_rfq_id");

                    b.Navigation("CurrentVersion");

                    b.Navigation("Customer");

                    b.Navigation("SourceRfq");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.QuotationLineItem", b =>
                {
                    b.HasOne("Maliev.QuotationService.Domain.Entities.QuotationVersion", "Version")
                        .WithMany("LineItems")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotation_line_items_quotation_versions_version_id");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.QuotationVersion", b =>
                {
                    b.HasOne("Maliev.QuotationService.Domain.Entities.Quotation", "Quotation")
                        .WithMany("Versions")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotation_versions_quotations_quotation_id");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Rfq", b =>
                {
                    b.HasOne("Maliev.QuotationService.Domain.Entities.Quotation", "ConvertedToQuotation")
                        .WithMany()
                        .HasForeignKey("ConvertedToQuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rfqs_quotations_converted_to_quotation_id");

                    b.HasOne("Maliev.QuotationService.Domain.Entities.Customer", "Customer")
                        .WithMany("Rfqs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rfqs_customers_customer_id");

                    b.Navigation("ConvertedToQuotation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message__outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_~");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("Rfqs");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Quotation", b =>
                {
                    b.Navigation("FileReferences");

                    b.Navigation("InternalNotes");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.QuotationVersion", b =>
                {
                    b.Navigation("DiscountStructures");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Maliev.QuotationService.Domain.Entities.Rfq", b =>
                {
                    b.Navigation("FileReferences");

                    b.Navigation("InternalNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
