// <auto-generated />
using System;
using System.Collections.Generic;
using Maliev.QuotationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.QuotationService.Data.Migrations
{
    [DbContext(typeof(QuotationDbContext))]
    partial class QuotationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId", "Timestamp");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MergeHistory")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<Guid>>("MergedFromIds")
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.DiscountStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorizationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Conditions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("QuotationVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuotationVersionId");

                    b.ToTable("discount_structures", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.FileReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadServiceFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.HasIndex("RfqId");

                    b.HasIndex("UploadServiceFileId")
                        .IsUnique();

                    b.ToTable("file_references", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileReference_Entity", "(\"RfqId\" IS NOT NULL AND \"QuotationId\" IS NULL) OR (\"RfqId\" IS NULL AND \"QuotationId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.InternalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RfqId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("QuotationId");

                    b.HasIndex("RfqId");

                    b.ToTable("internal_notes", null, t =>
                        {
                            t.HasCheckConstraint("CK_InternalNote_Entity", "(\"RfqId\" IS NOT NULL AND \"QuotationId\" IS NULL) OR (\"RfqId\" IS NULL AND \"QuotationId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.MaterialReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CachedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MaterialServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("MechanicalProperties")
                        .HasColumnType("jsonb");

                    b.Property<string>("PhysicalProperties")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("SupportedProcesses")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MaterialServiceId")
                        .IsUnique();

                    b.ToTable("material_references", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("SourceRfqId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValidityPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidityPeriodStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SourceRfqId");

                    b.HasIndex("Status");

                    b.HasIndex("ValidityPeriodEnd");

                    b.ToTable("quotations", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.QuotationLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ManufacturingProcess")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MaterialProperties")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("MaterialServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "LineNumber")
                        .IsUnique();

                    b.ToTable("quotation_line_items", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.QuotationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DeliveryExpectations")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecialTerms")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("quotation_versions", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Rfq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedStaffUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ChannelSource")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ConvertedToQuotationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RequestDetails")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffUserId");

                    b.HasIndex("ChannelSource");

                    b.HasIndex("ConvertedToQuotationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.HasIndex("ChannelSource", "Status", "CreatedAt");

                    b.ToTable("rfqs", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.StaffRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("staff_roles", (string)null);
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.DiscountStructure", b =>
                {
                    b.HasOne("Maliev.QuotationService.Data.Entities.QuotationVersion", "QuotationVersion")
                        .WithMany("DiscountStructures")
                        .HasForeignKey("QuotationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotationVersion");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.FileReference", b =>
                {
                    b.HasOne("Maliev.QuotationService.Data.Entities.Quotation", "Quotation")
                        .WithMany("FileReferences")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maliev.QuotationService.Data.Entities.Rfq", "Rfq")
                        .WithMany("FileReferences")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Quotation");

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.InternalNote", b =>
                {
                    b.HasOne("Maliev.QuotationService.Data.Entities.Quotation", "Quotation")
                        .WithMany("InternalNotes")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maliev.QuotationService.Data.Entities.Rfq", "Rfq")
                        .WithMany("InternalNotes")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Quotation");

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Quotation", b =>
                {
                    b.HasOne("Maliev.QuotationService.Data.Entities.QuotationVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maliev.QuotationService.Data.Entities.Customer", "Customer")
                        .WithMany("Quotations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maliev.QuotationService.Data.Entities.Rfq", "SourceRfq")
                        .WithMany()
                        .HasForeignKey("SourceRfqId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");

                    b.Navigation("Customer");

                    b.Navigation("SourceRfq");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.QuotationLineItem", b =>
                {
                    b.HasOne("Maliev.QuotationService.Data.Entities.QuotationVersion", "Version")
                        .WithMany("LineItems")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.QuotationVersion", b =>
                {
                    b.HasOne("Maliev.QuotationService.Data.Entities.Quotation", "Quotation")
                        .WithMany("Versions")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Rfq", b =>
                {
                    b.HasOne("Maliev.QuotationService.Data.Entities.Quotation", "ConvertedToQuotation")
                        .WithMany()
                        .HasForeignKey("ConvertedToQuotationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maliev.QuotationService.Data.Entities.Customer", "Customer")
                        .WithMany("Rfqs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConvertedToQuotation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Customer", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("Rfqs");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Quotation", b =>
                {
                    b.Navigation("FileReferences");

                    b.Navigation("InternalNotes");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.QuotationVersion", b =>
                {
                    b.Navigation("DiscountStructures");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Maliev.QuotationService.Data.Entities.Rfq", b =>
                {
                    b.Navigation("FileReferences");

                    b.Navigation("InternalNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
